<?
$con_play_arr=array('code'=>array('pk10X','pk5x','pk4x','pk3x','pk2x','pk1x'),'firstcode'=>'pk10X','lot_date'=>'','lot_num'=>'');
$con_title_arr=array(
  'pk10X'=>array('fullname'=>'定位胆','mode'=>''),
  'pk5x'=>array('fullname'=>'猜前五','mode'=>''),
  'pk4x'=>array('fullname'=>'猜前四','mode'=>''),
  'pk3x'=>array('fullname'=>'猜前三','mode'=>''),
  'pk2x'=>array('fullname'=>'猜前二','mode'=>''),
  'pk1x'=>array('fullname'=>'猜冠军','mode'=>'')
);

$con_code_arr=array(
  'pk10X'=>array(
      'pk10x'=>array('ListKey'=>'pk10x','CodeTile'=>'定位胆','ShowTile'=>'定位胆','Rebates'=>'Normal','MaxNote'=>'')
  ),
  'pk1x'=>array(
      'pk1x_fs'=>array('ListKey'=>'pk1x_fs','CodeTile'=>'前一','ShowTile'=>'复式','Rebates'=>'Normal','MaxNote'=>'')
  ),
  'pk2x'=>array(
      'pk2x_fs'=>array('ListKey'=>'pk2x_fs','CodeTile'=>'前二','ShowTile'=>'直选复式','Rebates'=>'Normal','MaxNote'=>''),
      'pk2x_ds'=>array('ListKey'=>'pk2x_ds','CodeTile'=>'前二','ShowTile'=>'直选单式','Rebates'=>'Normal','MaxNote'=>'')
  ),
  'pk3x'=>array(
      'pk3x_fs'=>array('ListKey'=>'pk3x_fs','CodeTile'=>'前三','ShowTile'=>'复式','Rebates'=>'Normal','MaxNote'=>''),
      'pk3x_ds'=>array('ListKey'=>'pk3x_ds','CodeTile'=>'前三','ShowTile'=>'单式','Rebates'=>'Normal','MaxNote'=>'')
  ),
  'pk4x'=>array(
      'pk4x_fs'=>array('ListKey'=>'pk4x_fs','CodeTile'=>'前四','ShowTile'=>'复式','Rebates'=>'Normal','MaxNote'=>''),
      'pk4x_ds'=>array('ListKey'=>'pk4x_ds','CodeTile'=>'前四','ShowTile'=>'单式','Rebates'=>'Normal','MaxNote'=>'')
  ),
  'pk5x'=>array(
      'pk5x_fs'=>array('ListKey'=>'pk5x_fs','CodeTile'=>'前五','ShowTile'=>'复式','Rebates'=>'Normal','MaxNote'=>''),
      'pk5x_ds'=>array('ListKey'=>'pk5x_ds','CodeTile'=>'前五','ShowTile'=>'单式','Rebates'=>'Normal','MaxNote'=>'')
  )
);
$con_play_pri=array(
  'QWX2_sxp'=>array('','','','2.2|4.00|2.2'),
  'QWX2_jep'=>array('','','','2.2|4.00|2.2'),
  'QWX2_hzdxds'=>array('','','','3.6'),
  'QWX2_5x'=>array('','','','8.6|4.4|2.3|4.4|8.6'),
  'RXX_rx1'=>array('','','','6.4'),
  'RXX_rx2'=>array('','','','25'),
  'RXX_rx3'=>array('','','','46|6'),
  'RXX_rx4'=>array('','','','110|12|3'),
  'RXX_rx5'=>array('','','','600|50|6'),
  'RXX_rx6'=>array('','','','1000|70|10|6'),
  'RXX_rx7'=>array('','','','10000|230|30|6|3'),
  'pk10x'=>array('','','','20'),
  'pk5x_fs'=>array('','','','58968'),
  'pk5x_ds'=>array('','','','58968'),
  'pk4x_fs'=>array('','','','9828'),
  'pk4x_ds'=>array('','','','9828'),
  'pk3x_fs'=>array('','','','1440'),
  'pk3x_ds'=>array('','','','1440'),
  'pk2x_fs'=>array('','','','180'),
  'pk2x_ds'=>array('','','','180'),
  'pk1x_fs'=>array('','','','20'),
  'pkds_2'=>array('','','','4'),
  'pkds_0'=>array('','','','4'),
  'pkds_1'=>array('','','','4'),
  'pkdx_0'=>array('','','','4'),
  'pkdx_2'=>array('','','','4'),
  'pkdx_1'=>array('','','','4')
);

$con_play_time=array(
  'QWX2_sxp'=>array('','',''),
  'QWX2_jep'=>array('','',''),
  'QWX2_hzdxds'=>array('','',''),
  'QWX2_5x'=>array('','',''),
  'RXX_rx1'=>array('','',''),
  'RXX_rx2'=>array('','',''),
  'RXX_rx3'=>array('','',''),
  'RXX_rx4'=>array('','',''),
  'RXX_rx5'=>array('','',''),
  'RXX_rx6'=>array('','',''),
  'RXX_rx7'=>array('','',''),
  'pk10x'=>array('','',''),
  'pk5x_fs'=>array('','',''),
  'pk5x_ds'=>array('','',''),
  'pk4x_fs'=>array('','',''),
  'pk4x_ds'=>array('','',''),
  'pk3x_fs'=>array('','',''),
  'pk3x_ds'=>array('','',''),
  'pk2x_fs'=>array('','',''),
  'pk2x_ds'=>array('','',''),
  'pk1x_fs'=>array('','',''),
  'pkds_2'=>array('','',''),
  'pkds_0'=>array('','',''),
  'pkds_1'=>array('','',''),
  'pkdx_0'=>array('','',''),
  'pkdx_2'=>array('','',''),
  'pkdx_1'=>array('','','')
);

?>