<?
$con_play_arr=array('code'=>array('pk10X','pk5x','pk4x','pk3x','pk2x','pk1x'),'firstcode'=>'pk10X','lot_date'=>'','lot_num'=>'');
$con_title_arr=array(
  'pk10X'=>array('fullname'=>'定位胆','mode'=>''),
  'pk5x'=>array('fullname'=>'猜前五','mode'=>''),
  'pk4x'=>array('fullname'=>'猜前四','mode'=>''),
  'pk3x'=>array('fullname'=>'猜前三','mode'=>''),
  'pk2x'=>array('fullname'=>'猜前二','mode'=>''),
  'pk1x'=>array('fullname'=>'猜冠军','mode'=>'')
);

$con_code_arr=array(
  'pk10X'=>array(
      'pk10x'=>array('ListKey'=>'pk10x','CodeTile'=>'定位胆','ShowTile'=>'定位胆','Rebates'=>'Normal','MaxNote'=>'')
  ),
  'pk1x'=>array(
      'pk1x_fs'=>array('ListKey'=>'pk1x_fs','CodeTile'=>'前一','ShowTile'=>'复式','Rebates'=>'Normal','MaxNote'=>'')
  ),
  'pk2x'=>array(
      'pk2x_fs'=>array('ListKey'=>'pk2x_fs','CodeTile'=>'前二','ShowTile'=>'直选复式','Rebates'=>'Normal','MaxNote'=>''),
      'pk2x_ds'=>array('ListKey'=>'pk2x_ds','CodeTile'=>'前二','ShowTile'=>'直选单式','Rebates'=>'Normal','MaxNote'=>'')
  ),
  'pk3x'=>array(
      'pk3x_fs'=>array('ListKey'=>'pk3x_fs','CodeTile'=>'前三','ShowTile'=>'复式','Rebates'=>'Normal','MaxNote'=>''),
      'pk3x_ds'=>array('ListKey'=>'pk3x_ds','CodeTile'=>'前三','ShowTile'=>'单式','Rebates'=>'Normal','MaxNote'=>'')
  ),
  'pk4x'=>array(
      'pk4x_fs'=>array('ListKey'=>'pk4x_fs','CodeTile'=>'前四','ShowTile'=>'复式','Rebates'=>'Normal','MaxNote'=>''),
      'pk4x_ds'=>array('ListKey'=>'pk4x_ds','CodeTile'=>'前四','ShowTile'=>'单式','Rebates'=>'Normal','MaxNote'=>'')
  ),
  'pk5x'=>array(
      'pk5x_fs'=>array('ListKey'=>'pk5x_fs','CodeTile'=>'前五','ShowTile'=>'复式','Rebates'=>'Normal','MaxNote'=>''),
      'pk5x_ds'=>array('ListKey'=>'pk5x_ds','CodeTile'=>'前五','ShowTile'=>'单式','Rebates'=>'Normal','MaxNote'=>'')
  )
);
$con_play_pri=array(
);

$con_play_time=array(
);

?>